# Generated by Django 2.2.1 on 2021-07-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kle_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='request_book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=50)),
                ('book_name', models.CharField(max_length=200)),
                ('book_author_name', models.CharField(max_length=200)),
                ('book_edition', models.CharField(max_length=200)),
                ('additional_info', models.CharField(max_length=500)),
            ],
        ),
    ]
