# Generated by Django 3.0.7 on 2021-07-24 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('Teacher', models.CharField(blank=True, max_length=100, null=True)),
                ('from_d', models.DateField()),
                ('to_d', models.DateField()),
                ('total_c', models.IntegerField()),
                ('attended_c', models.IntegerField()),
                ('remark', models.CharField(max_length=500)),
                ('posted_d', models.DateTimeField(default=django.utils.timezone.now)),
                ('stu_user', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
