# Generated by Django 3.0.7 on 2021-07-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20210724_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='Teacher',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='subject',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
