# Generated by Django 3.0.7 on 2021-07-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20210724_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='posted_d',
            field=models.CharField(max_length=100),
        ),
    ]
