# Generated by Django 3.0.7 on 2021-07-27 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0004_auto_20210726_0051'),
    ]

    operations = [
        migrations.CreateModel(
            name='performance_update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('teacher', models.CharField(max_length=100)),
                ('exam_name', models.CharField(max_length=100)),
                ('other_exam', models.CharField(max_length=100)),
                ('total_m', models.CharField(max_length=100)),
                ('obtained_m', models.CharField(max_length=100)),
                ('remark', models.CharField(max_length=100)),
                ('posted_d', models.CharField(max_length=100)),
                ('stu_name', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
