# Generated by Django 2.2.1 on 2021-07-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yourname', models.CharField(max_length=100)),
                ('youremail', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=50)),
                ('yourmessage', models.CharField(max_length=200)),
            ],
        ),
    ]
