# Generated by Django 2.2.1 on 2021-07-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stu_feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200)),
                ('fd1', models.CharField(max_length=20)),
                ('fd2', models.CharField(max_length=20)),
                ('fd3', models.CharField(max_length=20)),
                ('fd4', models.CharField(max_length=20)),
                ('fd5', models.CharField(max_length=20)),
                ('fd6', models.CharField(max_length=20)),
                ('fd7', models.CharField(max_length=500)),
            ],
        ),
    ]
