# Generated by Django 2.2.1 on 2021-07-07 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0003_parents_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='stf_feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200)),
                ('stf1', models.CharField(max_length=20)),
                ('stf2', models.CharField(max_length=20)),
                ('stf3', models.CharField(max_length=20)),
                ('stf4', models.CharField(max_length=20)),
                ('stf5', models.CharField(max_length=20)),
                ('stf6', models.CharField(max_length=20)),
                ('stf7', models.CharField(max_length=500)),
            ],
        ),
    ]
